name: Wine Quality ML Pipeline
owner: Liminal team
super: Infra
volumes:
  - volume: modelstore
    claim_name: modelstore-pvc
    local:
      path: .
variables:
  cluster_name: demo_emr_cluster
  ml_bucket: "s3://liminal-ml-bucket"
pipelines:
  - pipeline: wine_quality_pipeline
    start_date: 1970-01-01
    timeout_minutes: 45
    schedule: 0 * 1 * *
    metrics:
      namespace: DataScience
      backends: []
    tasks:
      - task: feature_engineering
        type: spark
        cluster_name: "{{cluster_name}}"
        application_source: 'data_pipeline.py'
        application_arguments:
          --input_uri: "http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
          --output_uri: "{{ml_bucket}}/features"
          --preprocess: "True"
          --features: ["fixed acidity","volatile acidity","citric acid","residual sugar","chlorides"]
