name: Running unittest

on: [push]

jobs:
  unittest:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Minikube
      uses: manusa/actions-setup-minikube@v2.3.0
      with:
        minikube version: 'v1.16.0'
        kubernetes version: 'v1.19.2'
        github token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - name: Install python requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run unittest
      run: ./run_tests.sh